"""
Maitain constant variable will be used in this program
"""
import numpy as np


LOAD = [1, 1, 1, 0, 0 ,0]

GLASS_EPOXY= 'glass_epoxy'
GRAPHITE_EPOXY = "graphite_epoxy"
CARBON_EPOXY = "carbon_epoxy"


GLASS_EPOXY_PROPERTIES     = {"E1":38.6,  "E2":8.27, "v12":0.26,  "G12":4.14 }
CARBON_EPOXY_PROPERTIES    = {"E1":116.6,  "E2":7.673, "v12":0.27,  "G12":4.173 }
GRAPHITE_EPOXY_PROPERTIES  = {"E1":181,  "E2":10.3, "v12":0.28,  "G12":7.17 }

CARBON_EPOXY_DENSITY = 1.605
GRAPHITE_EPOXY_DENSITY = 1.59
GLASS_EPOXY_DENSITY = 1.903

GLASS_EPOXY_COST = 1
GRAPHITE_EPOXY_COST = 2.5
CARBON_EPOXY_COST = 8

SAFETY_FACTOR = 2


# genetic algorithm parameter

POPULATION_NUMBER = 10 
MUTATION_PROBABILITY=0.8
CROSSOVER_PROBABLITY=0.8
ELITIST_PERCENT=0.40

# parents selection
PROPER_PARENTS_PERCENT = 0.3

PARENTS_BY_FITNESS_PERCENT = 0.4
prefix = "improved_" 
#prefix = "original_" 
#PARENTS_BY_FITNESS_PERCENT = 0.0

CHROMOSOME_LENGTH_LOWER_BOUND = 3 
CHROMOSOME_LENGTH_UPPER_BOUND = 15 
GA_RUNTIMES = 100
# Material
LAYER_HEIGHT = 0.000165
ANGLE = [np.pi/4]
#MATERIAL = [CARBON_EPOXY]
#MATERIAL = [GRAPHITE_EPOXY]
#MATERIAL = [GLASS_EPOXY]
MATERIAL = [GRAPHITE_EPOXY,GLASS_EPOXY]#GRAPHITE_EPOXY, GLASS_EPOXY] #CARBON_EPOXY #GLASS_EPOXY

